<a href="https://colab.research.google.com/github/AbhishekShah272002/Machine-Learning-Study./blob/main/Learning-Labs/Online_Retail.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df = pd.read_excel("Online Retail.xlsx")

In [21]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [23]:
df.shape

(541909, 8)

In [38]:
duplicate_rows = df[df.duplicated()]
print(duplicate_rows)

       InvoiceNo StockCode                        Description  Quantity  \
517       536409     21866        UNION JACK FLAG LUGGAGE TAG         1
527       536409     22866      HAND WARMER SCOTTY DOG DESIGN         1
537       536409     22900    SET 2 TEA TOWELS I LOVE LONDON          1
539       536409     22111       SCOTTIE DOG HOT WATER BOTTLE         1
555       536412     22327  ROUND SNACK BOXES SET OF 4 SKULLS         1
...          ...       ...                                ...       ...
541675    581538     22068        BLACK PIRATE TREASURE CHEST         1
541689    581538     23318     BOX OF 6 MINI VINTAGE CRACKERS         1
541692    581538     22992             REVOLVER WOODEN RULER          1
541699    581538     22694                       WICKER STAR          1
541701    581538     23343       JUMBO BAG VINTAGE CHRISTMAS          1

               InvoiceDate  UnitPrice  CustomerID         Country
517    2010-12-01 11:45:00       1.25     17908.0  United Kingdom
527    2010-12-01 11:45:00       2.10     17908.0  United Kingdom
537    2010-12-01 11:45:00       2.95     17908.0  United Kingdom
539    2010-12-01 11:45:00       4.95     17908.0  United Kingdom
555    2010-12-01 11:49:00       2.95     17920.0  United Kingdom
...                    ...        ...         ...             ...
541675 2011-12-09 11:34:00       0.39     14446.0  United Kingdom
541689 2011-12-09 11:34:00       2.49     14446.0  United Kingdom
541692 2011-12-09 11:34:00       1.95     14446.0  United Kingdom
541699 2011-12-09 11:34:00       2.10     14446.0  United Kingdom
541701 2011-12-09 11:34:00       2.08     14446.0  United Kingdom

[5225 rows x 8 columns]

In [40]:
duplicates_count = df.duplicated().sum()
print(duplicates_count)

5225

In [41]:
df.shape

(406829, 8)

In [24]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [25]:
df.dropna(subset=['Description'], inplace=True)

In [26]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133626
Country             0
dtype: int64

In [27]:
df.dropna(subset=['CustomerID'], inplace=True)

In [28]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [29]:
df.shape

(406829, 8)